site_name: !ENV [VERSION_TITLE, "eTaSL ROS2"]
site_description: How to get started with eTaSL in ROS2.
repo_url: https://gitlab.kuleuven.be/rob-expressiongraphs/ros2/etasl_ros2
edit_uri: edit/devel/documentation/docs/
copyright: "Santiago Iregui and Erwin AertbeliÃ«n, KU Leuven, 2024, <a href='https://etasl.pages.gitlab.kuleuven.be/_static/LICENSE.txt'>GNU Lesser General Public License v3</a>"
theme:
  name: "readthedocs"
  custom_dir: 'docs/overrides'
  # name: material
  features: 
    # - content.code.copy

nav:
  - 'Installation':
    - 'markdown/installation/regular_installation.md'
    - 'markdown/installation/docker.md'
  - 'Application Template':
    - 'markdown/template/application_template.md'
  - 'Basic Tutorials':
    - 'Preparing your application':
      - 'markdown/basic_tutorials/setup_configuration.md'
      - 'markdown/basic_tutorials/skills_configuration.md'
      - 'markdown/basic_tutorials/task_parameters.md'
    - 'Running the eTaSL lifecycle node':
      - 'markdown/basic_tutorials/execution.md'
    - 'Starting a task':
      - 'markdown/basic_tutorials/starting_a_task.md'
    - 'Outputting data':
      - 'markdown/basic_tutorials/monitoring_of_events.md' 
      - 'markdown/basic_tutorials/task_variables_to_topics.md' 
      - 'markdown/basic_tutorials/task_variables_to_csv_files.md'
    - 'Inputting data':
      - 'markdown/basic_tutorials/subscribing_to_ros_topics.md' 
      - 'markdown/basic_tutorials/intraprocess_communication.md' 
  - 'Intermediate tutorials':
    - 'Coordinating tasks and other nodes':
      - 'markdown/intermediate_tutorials/fsm_yasmin.md'
      - 'markdown/intermediate_tutorials/action_server.md'
      - 'markdown/intermediate_tutorials/behavior_tree.md' 
    - 'Debugging':
      - 'markdown/intermediate_tutorials/etasl_console.md'
  - 'Advanced tutorials':
    - 'I/O Handlers':
      - 'markdown/advanced_tutorials/input_handlers.md'
      - 'markdown/advanced_tutorials/output_handlers.md'
    - 'Robot Drivers':
      - 'markdown/advanced_tutorials/creating_robot_drivers.md'
      - 'markdown/advanced_tutorials/using_ros_control.md'
  - 'Extras':
    - 'markdown/extras/changelog.md'
    - 'markdown/extras/glossary.md'
    - 'markdown/extras/citations.md'
    - 'markdown/extras/how_to_contribute.md'

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - abbr
  # - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
        # custom_fences:
        # - name: mermaid
        #   class: mermaid
        #   format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - tables
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        use_pygments: true
        linenums_style: table
  # - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.superfences
  - pymdownx.details
    #- nl2br
    ##  - mdx_gh_links:
#      user: mkdocs
#      repo: mkdocs
#  - mkdocs-click
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  # - javascripts/mathjaxhelper.js
  # The following libs are used to enable the copy button (since readthedocs does not come with that by default) 
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.10/clipboard.min.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
  - javascripts/copy-to-clipboard.js
  # - https://unpkg.com/mermaid@10.9.3/dist/mermaid.esm.min.mjs

# The following some style aspects:
extra_css:
  - css/extra.css
  - css/copy-to-clipboard.css
  - css/navbar.css


#hooks:
#  - docs/hooks.py
# plugins:
#   - search
  # - mermaid2
#  - autorefs
#  - callouts
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_section_style: list
#            members_order: source
#            show_root_heading: true
#            show_source: false
#            show_signature_annotations: true

# watch:
#   - overrides